apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp-private-gh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp-private-gh 
  name: goapp-private-gh
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: goapp-private-gh 
